USE ROLE ACCOUNTADMIN;
USE DATABASE MFG_SENTINEL;
USE SCHEMA ANALYTICS;

CREATE TABLE IF NOT EXISTS MACHINE_ANALYSIS_EVENTS (
    EVENT_ID VARCHAR,
    EVENT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE VARCHAR,
    AIR_TEMPERATURE_K FLOAT,
    PROCESS_TEMPERATURE_K FLOAT,
    ROTATIONAL_SPEED_RPM FLOAT,
    TORQUE_NM FLOAT,
    TOOL_WEAR_MIN FLOAT,
    TEMPERATURE_DELTA FLOAT,
    POWER_PROXY FLOAT,
    WEAR_TORQUE_INTERACTION FLOAT,
    FAILURE_CLASS VARCHAR,
    FAILURE_PROBABILITY FLOAT,
    TWF_PROBABILITY FLOAT,
    HDF_PROBABILITY FLOAT,
    PWF_PROBABILITY FLOAT,
    OSF_PROBABILITY FLOAT,
    RNF_PROBABILITY FLOAT,
    RISK_LEVEL VARCHAR,
    PRIMARY_FAILURE_MODE VARCHAR,
    DIAGNOSIS VARCHAR,
    SENSOR_CONTEXT VARCHAR,
    RECOMMENDED_ACTION VARCHAR
);

CREATE TABLE IF NOT EXISTS INCIDENT_REGISTER (
    INCIDENT_ID VARCHAR,
    EVENT_ID VARCHAR,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    SEVERITY VARCHAR,
    STATUS VARCHAR,
    FAILURE_PROBABILITY FLOAT,
    FAILURE_CLASS VARCHAR,
    PRIMARY_FAILURE_MODE VARCHAR,
    DIAGNOSIS VARCHAR,
    SENSOR_CONTEXT VARCHAR,
    RECOMMENDED_ACTION VARCHAR,
    EMAIL_SENT BOOLEAN DEFAULT FALSE,
    RESOLUTION_NOTES VARCHAR,
    RESOLVED_AT TIMESTAMP_LTZ
);

-- For a restricted runtime role, grant only what the application needs:
-- GRANT USAGE ON DATABASE MFG_SENTINEL TO ROLE MFG_SENTINEL_APP_ROLE;
-- GRANT USAGE ON SCHEMA MFG_SENTINEL.ANALYTICS TO ROLE MFG_SENTINEL_APP_ROLE;
-- GRANT SELECT, INSERT, UPDATE
--   ON TABLE MFG_SENTINEL.ANALYTICS.MACHINE_ANALYSIS_EVENTS
--   TO ROLE MFG_SENTINEL_APP_ROLE;
-- GRANT SELECT, INSERT, UPDATE
--   ON TABLE MFG_SENTINEL.ANALYTICS.INCIDENT_REGISTER
--   TO ROLE MFG_SENTINEL_APP_ROLE;
-- GRANT USAGE ON INTEGRATION MFG_SENTINEL_EMAIL_INT
--   TO ROLE MFG_SENTINEL_APP_ROLE;
